services:
  - type: web
    name: bot-escanteios-rp-vip-plus
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot_escanteios_rp_vip_plus_multi_v2_economico.py"
    envVars:
      - key: TOKEN
        value: "7977015488:AAGFxg1f8RcJk-1b1pZEIBz7fnvs1IjKR50"
      - key: TELEGRAM_CHAT_ID
        value: "-1003188916464"
      - key: API_FOOTBALL_KEY
        value: "568a54d86135d702aa3200dee11ab2de"
      - key: LOG_LEVEL
        value: "DEBUG"
      - key: SCAN_INTERVAL
        value: "120"
      - key: RENOTIFY_MINUTES
        value: "5"